### ISSUE TITLE
Improve spacing in navigation

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/docs-vanilla-theme#15]
The spacing in navigation is not as it used to be:

- There is too much indentation in the left in second level links
- Second level links are too close to each other
- The open/close chevron is not centrally aligned in the vertical space
- The width of the left navigation is too large, it should be 300px not 350px
- When you click on a link from another section that isn't Settings, once the page loads only Settings is open. The section you just clicked on should be open

**Comment by barrymcgee** [comment]
This ticket is now obsolete due to new theme.
