### ISSUE TITLE
Design considerations

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/docs-vanilla-theme#3]
- [x] Content area correct in Jaas. Snapcraft has rounded corners in code blocks, which is not correct, and is missing space for anchor links on the right
- [x] Remove orange underline from current version (no underline)
- [x] We were going to only use chevrons for open/close icon, not mix chevron and plus
- [x] Remove underline from nav links (except versions)
- [x] Make titles in closed sections cool grey, not warm
- [x] Spacing in nav better in Snapcraft, in particular top/bottom padding in sections, but needs more bottom padding when section is open (should be the same as when section is closed)
- [x] The word "stable" looks bigger than version numbers, especially in small screen
- [x] If the docs are standalone, the menu icon in small screen has the docs nav, but what if the docs are inside another site with its own nav? Eg Jaas, Snapcraft
- [x] In small screen "Versions" title is larger than section titles, should be same or smaller
- [x] I'm thinking we need an indication that the person is looking at docs when the docs are inside another site. If you see the docs in Jaas on small screen, there is no title of the section visible. Something to consider
- [ ] Snapcraft is missing the search/version section above nav
- [ ] Where does the search box (inside docs) go in small screen?
- [ ] In Jaas, in small screen, the body copy doesn't align left with nav copy; in Snapcraft it does, and it looks better
- [ ] I think showing the entire (or even collapsed) main docs nav above the page content in small screen will not play well with the site's nav in some instances (eg. Snapcraft)
- [ ] Consider making anchor links menu fixed on large screen
- [ ] Would be nice to add some transition when the nav opens/closes

**Comment by barrymcgee** [comment]
These design considerations are based on the old theme and as such are now obsolete.
