### ISSUE TITLE
Background of images bleed into the background of the theme

### ISSUE THREAD

**Issue by pmatulis** [ubuntudesign/docs-vanilla-theme#31]
In the MAAS documentation, images of the MAAS web UI, which are most of our images, if not all, have their backgrounds bleed into the background of the maas.io/docs web site. The Docs team would like to have images professionally presented.

[Here](http://maas.io/docs/en/installconfig-commission-nodes) are a [few](http://maas.io/docs/en/installconfig-proxy) [examples](http://maas.io/docs/en/installconfig-subnets-dhcp).

I'm not sure how you intend to fix this but I found that adding a 1-pixel width, light orange colour to the image is effectively a solution. We would like to keep images pristine and not have to add such a change to them, for obvious reasons.

**Comment by nottrobin** [comment]
@pmatulis yes that makes absolute sense.

@yaili could you give an opinion on the best solution? Could all images have a standard border or shadow? What colour / width / opacity should it have? Is a similar pattern used in other places?

**Comment by pmahnke** [comment]
@yaili 

I think the answer might have to be something that looks like a subtle border?

.documentation__contents img, .documentation__contents.inner-wrapper img {
    max-width: 100%;
    padding: 2px;
    border: 1px solid #cdcdcd;
}

giving you something like the notes

![image](https://cloud.githubusercontent.com/assets/441217/19830619/7cc95248-9df3-11e6-89bd-8a22c15edf9c.png)

and

![image](https://cloud.githubusercontent.com/assets/441217/19830634/d0278b30-9df3-11e6-8f53-753bf1f9adac.png)

**Comment by yaili** [comment]
There was some discussion about this for the Vanilla site docs (not the theme yet) since the App Guide is using a grey background to solve the same issue, cf. http://design.ubuntu.com/apps/patterns/layouts 

Marcus was keen on us trying a grey background to frame the images before trying the grey border, to keep consistency, but if we leave this at the MAAS docs/site level before we make it a theme pattern I'm happy for it to be added in. Make sense?

**Comment by nottrobin** [comment]
@yaili I think that makes sense. It's okay to use @pmahnke's CSS as long as it stays local to the maas.io or docs.ubuntu.com codebase rather than the docs-vanilla-theme? I'll get that done.

**Comment by yaili** [comment]
Great, it will be a good test for the pattern before we propose it to the docs theme, if we like it.

**Comment by nottrobin** [comment]
I've added this [directly to the documentation-builder](https://github.com/CanonicalLtd/documentation-builder/pull/30/files#diff-55c5e98392066b552a6d6ffd3dfc395cR53) and built it [on docs.staging.ubuntu.com](http://docs.staging.ubuntu.com/maas/en/installconfig-commission-nodes).

I'm not sure what to do with this issue - I guess it should be left open until we decide how to solve this problem in the theme itself?

**Comment by nottrobin** [comment]
Todo, from https://github.com/ubuntudesign/vanilla-framework/issues/718#issuecomment-266446666:

- @nottrobin will implement a new utility class in docs-vanilla-theme to add border
- Name of class: image-frame
- For now, there is not option to turn off image-frame in the markdown file, but we might add this option in the future
- There will be a class in content area that indicates the area uses image-frame

**Comment by barrymcgee** [comment]
This issue was moved to ubuntudesign/vanilla-docs-theme#12
