### ISSUE TITLE
Navigation padding

### ISSUE THREAD

**Issue by deadlight** [ubuntudesign/docs-vanilla-theme#33]
### Issue

On the largest viewport, the padding on the left-side navigation has padding which grows relative to viewport width. 

This looks bad on larger screens ([see screenshot](http://www.awesomescreenshot.com/image/1776018/321d230556b020f3bbd47a57d63aebc3)).

### How to replicate

View a page using the theme with a left-menu a larger viewport.

**Comment by nottrobin** [comment]
This wasn't actually an issue with the theme, it was an issue with [my breadcrumbs work](https://github.com/nottrobin/documentation-builder/commit/d28e6e57e3a028be19aa209b5e05510a499735ae) which is now fixed. So closing.
