### ISSUE TITLE
Small screen docs navigation

### ISSUE THREAD

**Issue by spencerbygraves** [ubuntudesign/docs-vanilla-theme#46]
Here's the design. Each level will expand vertically, rather than in a page stack pattern as discussed before. Can we also look at the version select and breadcrumb being sticky when scrolling?

I've also included a design for the logo and title separator in the header.

![image](https://cloud.githubusercontent.com/assets/9105999/20758093/a4990594-b710-11e6-9c21-da3930b8d559.png)

![image](https://cloud.githubusercontent.com/assets/9105999/20758107/ab49453e-b710-11e6-8e1d-9574971d7b31.png)

**Comment by nottrobin** [comment]
@spencerbygraves Have you considered how that header will look in small screens if there *isn't* a word in the logo?

**Comment by nottrobin** [comment]
@spencerbygraves I'd also be concerned about the version select *and* breadcrumbs being sticky. This looks like it will often take up 3 lines and may easily take up 4 at the top of the screen, and on a fairly small mobile phone screen this will mean there's not a whole lot of space left to read the article.

**Comment by nottrobin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Spencer's further changes](https://trello.com/c/VfneA2YS/2261-spencer-s-further-changes)

**Comment by spencerbygraves** [comment]
@nottrobin I'll add a small screen version of the header without the title. I guess if there's no logo there's not much we can do, as the close and search would have to remain on the right. It will be an empty space on the left.

Perhaps we don't need the breadcrumb to be sticky, let's discuss it with Lil when she's back.

**Comment by spencerbygraves** [comment]
@nottrobin here's the headers without logo and title:

![image](https://cloud.githubusercontent.com/assets/9105999/20796214/11eb09d2-b7cd-11e6-9634-f1def234e31a.png)

**Comment by nottrobin** [comment]
@spencerbygraves sorry is there a plan for if there's no text in the logo? E.g. a logo like this:

![no-text](https://assets.ubuntu.com/v1/442ccba1-snappy-ubuntu-core-logo-01.svg)

**Comment by spencerbygraves** [comment]
@nottrobin if there's no text in the logo, I suggest we add the dividing line with the same spacing.

Perhaps it's better to align the text to the left then? Like this:

![image](https://cloud.githubusercontent.com/assets/9105999/20798719/ceb325fe-b7d7-11e6-8c62-fa67f02d93b3.png)

**Comment by barrymcgee** [comment]
This issue was moved to ubuntudesign/vanilla-docs-theme#18
