### ISSUE TITLE
Software version not apparent enough in the sidebar

### ISSUE THREAD

**Issue by pmatulis** [ubuntudesign/docs-vanilla-theme#47]
On http://docs.ubuntu.com/maas/2.1/en/ the selected version is not apparent enough. Can we highlight it better?

**Comment by nottrobin** [comment]
@yaili, @spencerbygraves any ideas?

**Comment by anthonydillon** [comment]
I agree, even more so on small screens. The version is art the bottom of the page and looks like this:

![screenshot_20161202-221746](https://cloud.githubusercontent.com/assets/1413534/20852368/66602090-b8dd-11e6-876e-084ddea1c4df.png)

**Comment by anthonydillon** [comment]
As we are using flex to layout the content can we swap the order of content so version and contents are above the main body text?

**Comment by yaili** [comment]
Did we say the current version should also have bottom border? Like the links on hover?

Regarding the order, the original idea was for the table of contents to be after the page's h1, like gov.uk, and similarly closed but I don't think there are designs for that.

**Comment by anthonydillon** [comment]
Could they be classed as tabs? Spencer has been exploring the tabbing styling.

Good to know. That would require duplicated content to be shown and hidden on threshold a breakpoint.

**Comment by nottrobin** [comment]
The latest small screen designs from spencer (https://github.com/ubuntudesign/docs-vanilla-theme/issues/46) haven't been implemented yet. They would put the version at the top of the screen on mobile, and make it more clear.

That doesn't solve the full-width layout though.

**Comment by spencerbygraves** [comment]
We agreed to use a select menu for the versions, on both small and large screen. We should try that first, and look at a new style if needed.

**Comment by barrymcgee** [comment]
This issue was moved to ubuntudesign/vanilla-docs-theme#17
