### ISSUE TITLE
Navigation right sidebar "Back to top" looks like a regular link

### ISSUE THREAD

**Issue by pmatulis** [ubuntudesign/docs-vanilla-theme#49]
The navigation right sidebar has a "Back to top" link that appears when the page is scrolled down. It ends up looking like a regular link. Can this be improved? For example, a new section can be added just for that one link:

```
VERSIONS

2.0  2.1

----------------

CONTENTS

link
link
link

----------------

Back to top
```

**Comment by spencerbygraves** [comment]
Thanks @pmatulis We're currently updating the docs theme design, this is one of the areas we're looking at.

**Comment by barrymcgee** [comment]
This issue was moved to ubuntudesign/vanilla-docs-theme#15
