### ISSUE TITLE
table of contents text wrapping is hard to read

### ISSUE THREAD

**Issue by pmahnke** [ubuntudesign/docs-vanilla-theme#51]
if you have long list elements, the links all blend together making it hard to read

![image](https://cloud.githubusercontent.com/assets/441217/20973319/21722418-bc90-11e6-8227-94950fdce37b.png)

perhaps a more generous margin would help, e.g.

``` css
.p-toc__item {
    margin-bottom: 1em;
}
```

which gives you

![image](https://cloud.githubusercontent.com/assets/441217/20973448/81f61df8-bc90-11e6-9b92-c3f234954c7c.png)

**Comment by barrymcgee** [comment]
This issue was moved to ubuntudesign/vanilla-docs-theme#8

**Comment by barrymcgee** [comment]
This issue was moved to ubuntudesign/vanilla-docs-theme#9
