### ISSUE TITLE
table of contents - spacing issue

### ISSUE THREAD

**Issue by magdalena-mirowicz** [ubuntudesign/docs-vanilla-theme#53]
when the heading wraps over 2 or more lines, you can't easily distinguish where one headings ends and new begins. Perhaps the line height should be different

Look at the attached screengrab

![screen shot 2016-12-08 at 16 25 50](https://cloud.githubusercontent.com/assets/16683435/21018005/2efbda92-bd63-11e6-9bbc-c781b6f5696d.png)

**Comment by barrymcgee** [comment]
This issue was moved to ubuntudesign/vanilla-docs-theme#6
