### ISSUE TITLE
table of contents: Should we reconsider the defaults?

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/docs-vanilla-theme#55]
Currently, it's off by default, and can be enabled with:

``` markdown
---
table_of_contents: true
---
```

I believe more pages *don't* need it than *do* because most pages are quite short. However, instead of manually turning it on, should we make it turn on when there are more than a certain number (e.g. `>= 4`) of headings to list?

I'd prefer enforcing a convention over configuration, unless there's a good argument for configuring it specifically.

**Comment by pmatulis** [comment]
The thing is that sometimes you have just 2 sub-headings but with a lot of text in between (makes sense to have a TOC in this case) and sometimes you have several sub-headings with very little text in between. Why do you want to default to enabled (or auto-enabled) and not let the writer decide?

**Comment by barrymcgee** [comment]
This issue was moved to ubuntudesign/vanilla-docs-theme#4
