### ISSUE TITLE
table of contents: Should "back to top" be more distinct?

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/docs-vanilla-theme#57]
I think we should make the "back to top" link stand out a bit more. Different colour? Different size? Icon?

**Comment by spencerbygraves** [comment]
I think we want to separate this link from the others, probably with a grey horizontal line.

Could you also look at this please? I think it makes sense - #51 

Thanks

**Comment by barrymcgee** [comment]
This issue was moved to ubuntudesign/vanilla-docs-theme#2
