### ISSUE TITLE
Table of contents design

### ISSUE THREAD

**Issue by spencerbygraves** [ubuntudesign/docs-vanilla-theme#58]
I've attached a design for the following issues:

- Back to top link separated from the other links
- Increased leading on wrapped links
- The current position is reflected in the selected link state
- Versions are in a select menu

![image](https://cloud.githubusercontent.com/assets/9105999/21183158/80f15d82-c1fe-11e6-94ff-8b51e8f1926b.png)

**Comment by pmatulis** [comment]
I find the placement of the version selector awkward. It is in the area that contains the page's internal navigation. It seems version should be placed somewhere at a higher hierarchical level. Can it be put to the right of the string 'Documentation' (separated from it with one of those vertical bars)? Another option would be to put it at the top of the menu on the left.

**Comment by spencerbygraves** [comment]
@pmatulis After a recent discussion, we feel it's at the correct level. The version selector works by being contextual to the page you are viewing, rather than a global level.

Also, the versions that you can view change depending on the page you are on.

**Comment by yaili** [comment]
@nottrobin should this be assigned to you?

**Comment by barrymcgee** [comment]
This issue was moved to ubuntudesign/vanilla-docs-theme#1
